spring.application.name: uploader-service

server.servlet.context-path: /uploads
server.port: 9050

eureka.client.service-url.defaultZone: http://localhost:8761/eureka

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

gcloud:
  storage-bucket-name: ${GCLOUD_STORAGE_BUCKET_NAME}
  storage-access-key: ${GCLOUD_SERVICE_ACCOUNT_JSON}
